config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

from rest_framework import routers

from gestion.views import HomeView

from gestion import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'administrateurs', views.AdministrateurViewSet)
router.register(r'formateurs', views.FormateurViewSet)
router.register(r'categories', views.CategorieViewSet)
router.register(r'formations', views.FormationViewSet)
router.register(r'apprenants', views.ApprenantViewSet)
router.register(r'regroupement', views.RegroupementViewSet)
router.register(r'cours', views.CoursViewSet)
router.register(r'chapitres', views.ChapitreViewSet)
router.register(r'ressources', views.RessourceViewSet)
router.register(r'animers', views.AnimerViewSet)
router.register(r'tests', views.TestViewSet)

urlpatterns = [
                  url(r'^$', HomeView.as_view(), name="home"),
                  url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # User management
                  url(r'^users/', include("tice_project.users.urls", namespace="users")),
                  url(r'^accounts/', include('allauth.urls')),

                  # Your stuff: custom urls includes go here
                  url(r'^gestion/', include('gestion.urls', namespace='gestion')),
                  url(r'^pv/', include('pv.urls', namespace='pv')),

                  # Apis
                  url(r'^api/', include(router.urls)),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion/urls.py
from django.conf.urls import url, include, patterns

from gestion import views

urlpatterns = [

    # urls for atomic function
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^logout-then-login/$', 'django.contrib.auth.views.logout_then_login', name='logout_then_login'),

    # change password urls
    url(r'^password-change/$', 'django.contrib.auth.views.password_change', name='password_change'),
    url(r'^password-change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),

    url(r'^register/$', views.register, name='register'),

    # CRUD (Categorie)
    url(
        regex=r'^categorie$',
        view=views.ListeCategorie.as_view(),
        name='dash_categorie'
    ),

    url(
        regex=r'^categorie/new$',
        view=views.CreateCategorie.as_view(),
        name='create_categ'

    ),

    url(
        regex=r'^categorie/edit/(?P<pk>\d+)$',
        view=views.UpdateCategorie.as_view(),
        name='update_categ'
    ),

    url(
        regex=r'^categorie/del/(?P<pk>\d+)$',
        view=views.DeleteCategorie.as_view(),
        name='delete_categ'
    ),

    # CRUD (Formateur)
    url(
        regex=r'^formateur$',
        view=views.ListeFormateur.as_view(),
        name='dash_formateur'
    ),

    url(
        regex=r'^formateur/new$',
        view=views.CreateFormateur.as_view(),
        name='create_formateur'
    ),

    url(
        regex=r'^formateur/edit/(?P<pk>\d+)$',
        view=views.UpdateFormateur.as_view(),
        name='update_formateur'
    ),

    url(
        regex=r'^formateur/del/(?P<pk>\d+)$',
        view=views.DeleteFormateur.as_view(),
        name='delete_formateur'
    ),

    # CRUD (Ressource)
    url(
        regex=r'^ressource$',
        view=views.ListeRessource.as_view(),
        name='dash_ressource'
    ),

    url(r'^ressource/new$', 'gestion.views.create_ressource', name='create_ressource'),


    url(
        regex=r'^ressource/edit/(?P<pk>\d+)$',
        view=views.UpdateRessource.as_view(),
        name='update_ressource'
    ),

    url(
        regex=r'^ressource/del/(?P<pk>\d+)$',
        view=views.DeleteRessource.as_view(),
        name='delete_ressource'
    ),

    # CRUD (Apprenant)
    url(
        regex=r'^apprenant$',
        view=views.ListeApprenant.as_view(),
        name='dash_apprenant'
    ),

    url(
        regex=r'^apprenant/new$',
        view=views.CreateApprenant.as_view(),
        name='create_apprenant'
    ),

    url(
        regex=r'^apprenant/edit/(?P<pk>\d+)$',
        view=views.UpdateApprenant.as_view(),
        name='update_apprenant'
    ),

    url(
        regex=r'^apprenant/del/(?P<pk>\d+)$',
        view=views.DeleteApprenant.as_view(),
        name='delete_apprenant'
    ),

    # CRUD (Animer)
    url(
        regex=r'^anime$',
        view=views.ListeAnimation.as_view(),
        name='dash_anime'
    ),

    url(
        regex=r'^anime/new$',
        view=views.CreateAnimation.as_view(),
        name='create_anime'
    ),

    url(
        regex=r'^anime/edit/(?P<pk>\d+)$',
        view=views.UpdateAnimation.as_view(),
        name='update_anime'
    ),

    url(
        regex=r'^anime/del/(?P<pk>\d+)$',
        view=views.DeleteAnimation.as_view(),
        name='delete_anime'
    ),

    # CRUD (Chapitre)
    url(
        regex=r'^chapitre$',
        view=views.ListeChapitre.as_view(),
        name='dash_chapitre'
    ),

    url(
        regex=r'^chapitre/new$',
        view=views.CreateChapitre.as_view(),
        name='create_chapitre'
    ),

    url(
        regex=r'^chapitre/edit/(?P<pk>\d+)$',
        view=views.UpdateChapitre.as_view(),
        name='update_chapitre'
    ),

    url(
        regex=r'^chapitre/del/(?P<pk>\d+)$',
        view=views.DeleteChapitre.as_view(),
        name='delete_chapitre'
    ),

    # CRUD (Regroupement)
    url(
        regex=r'^regroup',
        view=views.ListeRegroupement.as_view(),
        name='dash_regroup'
    ),

    url(
        regex=r'^reg/new$',
        view=views.CreateRegroupement.as_view(),
        name='create_reg'
    ),

    url(
        regex=r'^reg/edit/(?P<pk>\d+)$',
        view=views.UpdateRegroupement.as_view(),
        name='update_reg'
    ),

    url(
        regex=r'^reg/del/(?P<pk>\d+)$',
        view=views.DeleteRegroupement.as_view(),
        name='delete_reg'
    ),

    # CRUD (Test)
    url(
        regex=r'^test',
        view=views.ListeTest.as_view(),
        name='dash_test'
    ),

    url(
        regex=r'^t/new$',
        view=views.CreateTest.as_view(),
        name='create_t'
    ),

    url(
        regex=r'^t/del/(?P<pk>\d+)$',
        view=views.DeleteTest.as_view(),
        name='delete_t'
    ),

    url(
        regex=r'^t/edit/(?P<pk>\d+)$',
        view=views.UpdateTest.as_view(),
        name='update_t'
    ),

    # CRUD (Cours)
    url(
        regex=r'^cours',
        view=views.ListeCours.as_view(),
        name='dash_cours'
    ),

    url(
        regex=r'^cour/new$',
        view=views.CreateCours.as_view(),
        name='create_cour'
    ),

    url(
        regex=r'^cour/del/(?P<pk>\d+)$',
        view=views.DeleteCours.as_view(),
        name='delete_cour'
    ),

    url(
        regex=r'^cour/edit/(?P<pk>\d+)$',
        view=views.UpdateCours.as_view(),
        name='update_cour'
    ),

    # READ(Consultation)
    url(
        regex=r'^consultation$',
        view=views.ConsultationView.as_view(),
        name='dash_consul'
    ),
]

pv/urls.py
from django.conf.urls import url, include, patterns

from pv import views

urlpatterns = [

    url(r'^apprenant/pdf/info/etudiant$', views.note_apprenant, name='etudiant_pdf'),
    url(r'^apprenant/dash$', views.PVApprenantView.as_view(), name='dash_apprenant'),
    url(r'^formateur/dash$', views.PVFormateurView.as_view(), name='dash_formateur'),
    url(r'^formateur/dash/info/liste$', views.all_apprenant, name='all_apprenant'),
]

tice_project/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

]

tice_project/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

gestion/forms.py
from django import forms

from gestion.models import Categorie, Formateur, Ressource, Apprenant, Chapitre, Animer, Regroupement, Test, Cours
from tice_project.users.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'last_name', 'first_name', 'email',)

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class CategorieForm(forms.ModelForm):
    class Meta:
        model = Categorie
        fields = ('lib_categ',)


class FormateurForm(forms.ModelForm):
    class Meta:
        model = Formateur
        fields = ('user', 'spec_formation', 'type_formation',)


class ApprenantForm(forms.ModelForm):
    class Meta:
        model = Apprenant
        fields = ('user', 'grade_util', 'diplome_appr', 'formation',)


class RessourceForm(forms.ModelForm):
    class Meta:
        model = Ressource
        fields = ('lib_ress', 'type_ress', 'chapitre',)

    docfile = forms.FileField(
        label='joindre un fichier',
        help_text='max. 42 megabytes')


class ChapitreForm(forms.ModelForm):
    class Meta:
        model = Chapitre
        fields = ('lib_chap', 'cours',)


class AnimerForm(forms.ModelForm):
    class Meta:
        model = Animer
        fields = ('id_util', 'id_form',)


class RegroupementForm(forms.ModelForm):
    class Meta:
        model = Regroupement
        fields = ('date_group', 'formation',)


class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ('id_util', 'id_form', 'date_test', 'note_test',)


class CoursForm(forms.ModelForm):
    class Meta:
        model = Cours
        fields = ('lib_cour', 'formation',)

tice_project/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

tice_project/templates/gestion/admin/apprenant_create_form.html
{% extends "gestion/dashboard.html" %}

{% block content2 %}

    <div class="row">
        <form action="{% url "gestion:create_apprenant" %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Valider"/>

        </form>
    </div>

{% endblock %}

tice_project/templates/gestion/admin/apprenant_delete.html
<h1>Êtes-vous sûr de vouloir supprimer cette URL ?</h1>

<p>voulez vous supprimer : {{ apprenant.user.last_name }} {{ apprenant.user.first_name }}</p>

<form method="post" action="">
    {% csrf_token %}
    <input type="submit" value="Oui supprime moi ça">
    <a href="{% url "gestion:dash_apprenant" %}">non, pas tout de suite</a>
</form>

tice_project/templates/gestion/admin/apprenant_update_form.html
{% extends "gestion/dashboard.html" %}

{% block content2 %}

    <div class="row">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Valider"/>

        </form>
    </div>

{% endblock %}

tice_project/templates/gestion/admin/categorie_create_form.html
{% extends "gestion/dashboard.html" %}

{% block content2 %}

    <div class="row">
        <form action="{% url "gestion:create_categ" %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Valider"/>

        </form>
    </div>

{% endblock %}

tice_project/templates/gestion/admin/categorie_delete.html
<h1>Êtes-vous sûr de vouloir supprimer cette URL ?</h1>

<p>voulez vous supprimer : {{ categorie.lib_categ }}</p>

<form method="post" action="">
    {% csrf_token %}
    <input type="submit" value="Oui supprime moi ça">
    <a href="{% url "gestion:dash_categorie" %}">non, pas tout de suite</a>
</form>

tice_project/templates/gestion/admin/categorie_update_form.html
{% extends "gestion/dashboard.html" %}

{% block content2 %}

    <div class="row">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Valider"/>

        </form>
    </div>

{% endblock %}

tice_project/templates/gestion/admin/dash_admin_apprenant.html
{% extends "gestion/dashboard.html" %}
{#{% block title %}Dashboard cotegorie{% endblock %}#}
{% block content2 %}

    <span class="mdl-layout-title">Apprenant</span>

    {% for article in derniers_articles %}
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--1-col">

                <div class="demo-card-event mdl-card mdl-shadow--2dp">
                    <div class=" mdl-card--expand">
                        <h4>
                            <p class="me_card"><strong>Username: </strong> {{ article.user.username }}</p>
                        </h4>
                        <p class="me_card"><strong>Grade : </strong> {{ article.grade_util }}</p>
                        <p class="me_card"><strong>Diplome : </strong> {{ article.diplome_appr }}</p>
                        <p class="me_card"><strong>Formation : </strong> {{ article.formation.lib_form }}</p>


                    </div>
                    <div class="mdl-card__actions mdl-card--border">
                        <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                           href="{% url "gestion:update_apprenant" article.id %}">
                            Modifier
                        </a>

                        <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                           href="{% url "gestion:delete_apprenant" article.id %}">
                            Supprimer
                        </a>
                        <div class="mdl-layout-spacer"></div>
                        <i class="material-icons">event</i>
                    </div>
                </div>
            </div>

        </div>

    {% endfor %}

    <a href="{% url "gestion:create_apprenant" %}" target="_blank" id="view-source"
       class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--accent mdl-color-text--accent-contrast">Ajouter</a>

{% endblock %}

tice_project/templates/gestion/admin/dash_admin_categorie.html
{% extends "gestion/dashboard.html" %}
{#{% block title %}Dashboard cotegorie{% endblock %}#}
{% block content2 %}

    <span class="mdl-layout-title">Categorie</span>

    {% for article in derniers_articles %}
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--1-col">

                <div class="demo-card-event mdl-card mdl-shadow--2dp">
                    <div class=" mdl-card--expand">
                        <h4>
                            <p class="me_card"><strong>Libelle Categorie: </strong> {{ article.lib_categ }}</p>
                        </h4>
                        <p class="me_card"><strong>ajoute par : </strong>{{ article.administrateur.user.username }}</p>
                        <p class="me_card"><strong>ajoute le : </strong>{{ article.created }}</p>
                        <p class="me_card"><strong>modifie le : </strong>{{ article.modified }}</p>

                    </div>
                    <div class="mdl-card__actions mdl-card--border">
                        <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                           href="{% url "gestion:update_categ" article.id %}">
                            Modifier
                        </a>

                        <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                           href="{% url "gestion:delete_categ" article.id %}">
                            Supprimer
                        </a>
                        <div class="mdl-layout-spacer"></div>
                        <i class="material-icons">event</i>
                    </div>
                </div>
            </div>

        </div>

    {% endfor %}

    <a href="{% url "gestion:create_categ" %}" target="_blank" id="view-source"
       class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--accent mdl-color-text--accent-contrast">Ajouter</a>

{% endblock %}

tice_project/templates/gestion/admin/dash_admin_formateur.html
{% extends "gestion/dashboard.html" %}
{#{% block title %}Dashboard cotegorie{% endblock %}#}
{% block content2 %}

    <span class="mdl-layout-title">Formateur</span>

    {% for article in derniers_articles %}
        <div class="mdl-grid">
            <div class="mdl-cell mdl-cell--1-col">

                <div class="demo-card-event mdl-card mdl-shadow--2dp">
                    <div class=" mdl-card--expand">
                        <h4>
                            <p class="me_card"><strong>Username: </strong> {{ article.user.username }}</p>
                        </h4>
                        <p class="me_card"><strong>Specialite : </strong> {{ article.spec_formation }}</p>
                        <p class="me_card"><strong>Type : </strong> {{ article.type_formation }}</p>

                    </div>
                    <div class="mdl-card__actions mdl-card--border">
                        <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                           href="{% url "gestion:update_formateur" article.id %}">
                            Modifier
                        </a>

                        <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
                           href="{% url "gestion:delete_formateur" article.id %}">
                            Supprimer
                        </a>
                        <div class="mdl-layout-spacer"></div>
                        <i class="material-icons">event</i>
                    </div>
                </div>
            </div>

        </div>

    {% endfor %}

    <a href="{% url "gestion:create_formateur" %}" target="_blank" id="view-source"
       class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--accent mdl-color-text--accent-contrast">Ajouter</a>

{% endblock %}

tice_project/templates/gestion/admin/formateur_create_form.html
{% extends "gestion/dashboard.html" %}

{% block content2 %}

    <div class="row">
        <form action="{% url "gestion:create_formateur" %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Valider"/>

        </form>
    </div>

{% endblock %}

tice_project/templates/gestion/admin/formateur_delete.html
<h1>Êtes-vous sûr de vouloir supprimer cette URL ?</h1>

<p>voulez vous supprimer : {{ formateur.last_name }} {{ formateur.first_name }}</p>

<form method="post" action="">
    {% csrf_token %}
    <input type="submit" value="Oui supprime moi ça">
    <a href="{% url "gestion:dash_categorie" %}">non, pas tout de suite</a>
</form>

tice_project/templates/gestion/admin/formateur_update_form.html
{% extends "gestion/dashboard.html" %}

{% block content2 %}

    <div class="row">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Valider"/>

        </form>
    </div>

{% endblock %}