config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

from rest_framework import routers

from gestion.views import HomeView

from gestion import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'administrateurs', views.AdministrateurViewSet)
router.register(r'formateurs', views.FormateurViewSet)
router.register(r'categories', views.CategorieViewSet)
router.register(r'formations', views.FormationViewSet)
router.register(r'apprenants', views.ApprenantViewSet)
router.register(r'regroupement', views.RegroupementViewSet)
router.register(r'cours', views.CoursViewSet)
router.register(r'chapitres', views.ChapitreViewSet)
router.register(r'ressources', views.RessourceViewSet)
router.register(r'animers', views.AnimerViewSet)
router.register(r'tests', views.TestViewSet)

urlpatterns = [
                  url(r'^$', HomeView.as_view(), name="home"),
                  url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # User management
                  url(r'^users/', include("tice_project.users.urls", namespace="users")),
                  url(r'^accounts/', include('allauth.urls')),

                  # Your stuff: custom urls includes go here
                  url(r'^gestion/', include('gestion.urls', namespace='gestion')),
                  url(r'^pv/', include('pv.urls', namespace='pv')),

                  # Apis
                  url(r'^api/', include(router.urls)),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pv/urls.py
from django.conf.urls import url, include, patterns

from pv import views

urlpatterns = [

    url(r'^apprenant/pdf/info/etudiant$', views.note_apprenant, name='etudiant_pdf'),
    url(r'^apprenant/dash$', views.PVApprenantView.as_view(), name='dash_apprenant'),
    url(r'^formateur/dash$', views.PVFormateurView.as_view(), name='dash_formateur'),
    url(r'^formateur/dash/info/liste$', views.all_apprenant, name='all_apprenant'),
]

tice_project/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

]

pv/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

tice_project/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

pv/views.py
from django.shortcuts import get_object_or_404

# Create your views here.
from django.views.generic import TemplateView

from gestion.models import Apprenant
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint


def note_apprenant(request):
    article = get_object_or_404(Apprenant, id=request.user.apprenant.id)
    html = render_to_string('pv/notes_apprenant.html', {'article': article})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=\"apprenant.pdf"'
    weasyprint.HTML(string=html).write_pdf(response,
                                           stylesheets=[weasyprint.CSS(settings.STATIC_ROOT + 'css/pdf.css')])
    return response


class PVApprenantView(TemplateView):
    template_name = "pv/dash_pv_apprenant.html"


def all_apprenant(request):
    article = Apprenant.objects.all()
    html = render_to_string('pv/all_apprenant.html', {'article': article})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=\"apprenant.pdf"'
    weasyprint.HTML(string=html).write_pdf(response,
                                           stylesheets=[weasyprint.CSS(settings.STATIC_ROOT + 'css/pdf.css')])
    return response


class PVFormateurView(TemplateView):
    template_name = "pv/dash_pv_formateur.html"

tice_project/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

tice_project/templates/pv/all_apprenant.html
<html>
<body>
<h1>Liste des appreant</h1>
<br/>
{% for ex in article %}
<ul>
    <li><strong>Nome : </strong>{{ ex.user.last_name }}</li>
    <li><strong>prenom : </strong>{{ ex.user.fist_name }}</li>
    <li><strong>email : </strong>{{ ex.user.email }}</li>
    <li><strong>Date inscription dans la plateforme : </strong>{{ ex.user.date_joined }}</li>
</ul>

<h3>Inscrit dans la formation suivante : </h3>
<ul>
    <li><strong>Libellé formation : </strong>{{ ex.formation.lib_form }}</li>
    <li><strong>Début de la formation : </strong>{{ ex.formation.date_deb_form }}</li>
    <li><strong>Fin de la formation : </strong>{{ ex.formation.date_fin_form }}</li>
    <li><strong>Catégorie de la formation : </strong>{{ ex.formation.categorie.lib_categ }}</li>

</ul>
{% endfor %}
</body>
</html>

tice_project/templates/pv/dash_pv_apprenant.html
{% extends "gestion/dashboard.html" %}

{% block content2 %}

    <h2>Liste des PV</h2>
    <a href="{% url "pv:etudiant_pdf" %}">Information de l'etudiant</a>

{% endblock %}

tice_project/templates/pv/dash_pv_formateur.html
{% extends "gestion/dashboard.html" %}

{% block content2 %}

    <h2>Liste des PV</h2>
    <a href="{% url "pv:all_apprenant" %}">Liste des etudiants</a>

{% endblock %}

tice_project/templates/pv/notes_apprenant.html
<html>
<body>
<h1>Information Etudiant</h1>
<br/>
<ul>
    <li><strong>Nome : </strong>{{ article.user.last_name }}</li>
    <li><strong>prenom : </strong>{{ article.user.fist_name }}</li>
    <li><strong>email : </strong>{{ article.user.email }}</li>
    <li><strong>Date inscription dans la plateforme : </strong>{{ article.user.date_joined }}</li>
</ul>

<h3>Inscrit dans la formation suivante : </h3>
<ul>
    <li><strong>Libellé formation : </strong>{{ article.formation.lib_form }}</li>
    <li><strong>Début de la formation : </strong>{{ article.formation.date_deb_form }}</li>
    <li><strong>Fin de la formation : </strong>{{ article.formation.date_fin_form }}</li>
    <li><strong>Catégorie de la formation : </strong>{{ article.formation.categorie.lib_categ }}</li>

</ul>
</body>
</html>