config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

from rest_framework import routers

from gestion.views import HomeView

from gestion import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'administrateurs', views.AdministrateurViewSet)
router.register(r'formateurs', views.FormateurViewSet)
router.register(r'categories', views.CategorieViewSet)
router.register(r'formations', views.FormationViewSet)
router.register(r'apprenants', views.ApprenantViewSet)
router.register(r'regroupement', views.RegroupementViewSet)
router.register(r'cours', views.CoursViewSet)
router.register(r'chapitres', views.ChapitreViewSet)
router.register(r'ressources', views.RessourceViewSet)
router.register(r'animers', views.AnimerViewSet)
router.register(r'tests', views.TestViewSet)

urlpatterns = [
                  url(r'^$', HomeView.as_view(), name="home"),
                  url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # User management
                  url(r'^users/', include("tice_project.users.urls", namespace="users")),
                  url(r'^accounts/', include('allauth.urls')),

                  # Your stuff: custom urls includes go here
                  url(r'^gestion/', include('gestion.urls', namespace='gestion')),
                  url(r'^pv/', include('pv.urls', namespace='pv')),

                  # Apis
                  url(r'^api/', include(router.urls)),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion/urls.py
from django.conf.urls import url, include, patterns

from gestion import views

urlpatterns = [

    # urls for atomic function
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^logout-then-login/$', 'django.contrib.auth.views.logout_then_login', name='logout_then_login'),

    # change password urls
    url(r'^password-change/$', 'django.contrib.auth.views.password_change', name='password_change'),
    url(r'^password-change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),

    url(r'^register/$', views.register, name='register'),

    # CRUD (Categorie)
    url(
        regex=r'^categorie$',
        view=views.ListeCategorie.as_view(),
        name='dash_categorie'
    ),

    url(
        regex=r'^categorie/new$',
        view=views.CreateCategorie.as_view(),
        name='create_categ'

    ),

    url(
        regex=r'^categorie/edit/(?P<pk>\d+)$',
        view=views.UpdateCategorie.as_view(),
        name='update_categ'
    ),

    url(
        regex=r'^categorie/del/(?P<pk>\d+)$',
        view=views.DeleteCategorie.as_view(),
        name='delete_categ'
    ),

    # CRUD (Formateur)
    url(
        regex=r'^formateur$',
        view=views.ListeFormateur.as_view(),
        name='dash_formateur'
    ),

    url(
        regex=r'^formateur/new$',
        view=views.CreateFormateur.as_view(),
        name='create_formateur'
    ),

    url(
        regex=r'^formateur/edit/(?P<pk>\d+)$',
        view=views.UpdateFormateur.as_view(),
        name='update_formateur'
    ),

    url(
        regex=r'^formateur/del/(?P<pk>\d+)$',
        view=views.DeleteFormateur.as_view(),
        name='delete_formateur'
    ),

    # CRUD (Ressource)
    url(
        regex=r'^ressource$',
        view=views.ListeRessource.as_view(),
        name='dash_ressource'
    ),

    url(r'^ressource/new$', 'gestion.views.create_ressource', name='create_ressource'),


    url(
        regex=r'^ressource/edit/(?P<pk>\d+)$',
        view=views.UpdateRessource.as_view(),
        name='update_ressource'
    ),

    url(
        regex=r'^ressource/del/(?P<pk>\d+)$',
        view=views.DeleteRessource.as_view(),
        name='delete_ressource'
    ),

    # CRUD (Apprenant)
    url(
        regex=r'^apprenant$',
        view=views.ListeApprenant.as_view(),
        name='dash_apprenant'
    ),

    url(
        regex=r'^apprenant/new$',
        view=views.CreateApprenant.as_view(),
        name='create_apprenant'
    ),

    url(
        regex=r'^apprenant/edit/(?P<pk>\d+)$',
        view=views.UpdateApprenant.as_view(),
        name='update_apprenant'
    ),

    url(
        regex=r'^apprenant/del/(?P<pk>\d+)$',
        view=views.DeleteApprenant.as_view(),
        name='delete_apprenant'
    ),

    # CRUD (Animer)
    url(
        regex=r'^anime$',
        view=views.ListeAnimation.as_view(),
        name='dash_anime'
    ),

    url(
        regex=r'^anime/new$',
        view=views.CreateAnimation.as_view(),
        name='create_anime'
    ),

    url(
        regex=r'^anime/edit/(?P<pk>\d+)$',
        view=views.UpdateAnimation.as_view(),
        name='update_anime'
    ),

    url(
        regex=r'^anime/del/(?P<pk>\d+)$',
        view=views.DeleteAnimation.as_view(),
        name='delete_anime'
    ),

    # CRUD (Chapitre)
    url(
        regex=r'^chapitre$',
        view=views.ListeChapitre.as_view(),
        name='dash_chapitre'
    ),

    url(
        regex=r'^chapitre/new$',
        view=views.CreateChapitre.as_view(),
        name='create_chapitre'
    ),

    url(
        regex=r'^chapitre/edit/(?P<pk>\d+)$',
        view=views.UpdateChapitre.as_view(),
        name='update_chapitre'
    ),

    url(
        regex=r'^chapitre/del/(?P<pk>\d+)$',
        view=views.DeleteChapitre.as_view(),
        name='delete_chapitre'
    ),

    # CRUD (Regroupement)
    url(
        regex=r'^regroup',
        view=views.ListeRegroupement.as_view(),
        name='dash_regroup'
    ),

    url(
        regex=r'^reg/new$',
        view=views.CreateRegroupement.as_view(),
        name='create_reg'
    ),

    url(
        regex=r'^reg/edit/(?P<pk>\d+)$',
        view=views.UpdateRegroupement.as_view(),
        name='update_reg'
    ),

    url(
        regex=r'^reg/del/(?P<pk>\d+)$',
        view=views.DeleteRegroupement.as_view(),
        name='delete_reg'
    ),

    # CRUD (Test)
    url(
        regex=r'^test',
        view=views.ListeTest.as_view(),
        name='dash_test'
    ),

    url(
        regex=r'^t/new$',
        view=views.CreateTest.as_view(),
        name='create_t'
    ),

    url(
        regex=r'^t/del/(?P<pk>\d+)$',
        view=views.DeleteTest.as_view(),
        name='delete_t'
    ),

    url(
        regex=r'^t/edit/(?P<pk>\d+)$',
        view=views.UpdateTest.as_view(),
        name='update_t'
    ),

    # CRUD (Cours)
    url(
        regex=r'^cours',
        view=views.ListeCours.as_view(),
        name='dash_cours'
    ),

    url(
        regex=r'^cour/new$',
        view=views.CreateCours.as_view(),
        name='create_cour'
    ),

    url(
        regex=r'^cour/del/(?P<pk>\d+)$',
        view=views.DeleteCours.as_view(),
        name='delete_cour'
    ),

    url(
        regex=r'^cour/edit/(?P<pk>\d+)$',
        view=views.UpdateCours.as_view(),
        name='update_cour'
    ),

    # READ(Consultation)
    url(
        regex=r'^consultation$',
        view=views.ConsultationView.as_view(),
        name='dash_consul'
    ),
]

pv/urls.py
from django.conf.urls import url, include, patterns

from pv import views

urlpatterns = [

    url(r'^apprenant/pdf/info/etudiant$', views.note_apprenant, name='etudiant_pdf'),
    url(r'^apprenant/dash$', views.PVApprenantView.as_view(), name='dash_apprenant'),
    url(r'^formateur/dash$', views.PVFormateurView.as_view(), name='dash_formateur'),
    url(r'^formateur/dash/info/liste$', views.all_apprenant, name='all_apprenant'),
]

tice_project/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

]

tice_project/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

tice_project/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

tice_project/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="fr">
<head>
    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="TICE platform">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock %}

    <title>{% block title %}TICE Project{% endblock %}</title>
    <!-- Page styles -->
    {% block css %}
        <link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en"
              rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/material.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% endblock %}
</head>

<body>

<!-- Always shows a header, even in smaller screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <div class="mdl-layout__drawer-button" tabindex="0" role="button" aria-expanded="false"><i
                    class="material-icons"></i>
            </div>
            <span class="mdl-layout-title">TICE</span>
            <!-- Add spacer, to align navigation to the right -->
            <div class="mdl-layout-spacer"></div>
            <!-- Navigation. We hide it in small screens. -->
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                <a class="mdl-navigation__link" href="{% url "home" %}">Home</a>
                <a class="mdl-navigation__link" href="{% url 'about' %}">About</a>
                {% if request.user.is_authenticated %}
                    <a class="mdl-navigation__link"
                       href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a>
                    <a class="mdl-navigation__link" href="{% url 'gestion:logout' %}">{% trans "Logout" %}</a>
                {% else %}
                    <a id="sign-up-link" class="mdl-navigation__link"
                       href="{% url 'gestion:register' %}">{% trans "Sign Up" %}</a>
                    <a id="log-in-link" class="mdl-navigation__link"
                       href="{% url 'gestion:login' %}">{% trans "Log In" %}</a>
                {% endif %}
            </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Title</span>

        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="{% url "home" %}">Home</a>
            <a class="mdl-navigation__link" href="{% url 'about' %}">About</a>
            {% if request.user.is_authenticated %}
                <a class="mdl-navigation__link"
                   href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a>
                <a class="mdl-navigation__link" href="{% url 'gestion:logout' %}">{% trans "Logout" %}</a>
            {% else %}
                <a id="sign-up-link" class="mdl-navigation__link"
                   href="{% url 'gestion:register' %}">{% trans "Sign Up" %}</a>
                <a id="log-in-link" class="mdl-navigation__link"
                   href="{% url 'gestion:login' %}">{% trans "Log In" %}</a>
            {% endif %}

            <a class="mdl-navigation__link" href="">Link</a>
            <a class="mdl-navigation__link" href="">Link</a>
        </nav>
    </div>
    <main class="mdl-layout__content">
        <div class="page-content">
            <!-- Your content goes here -->
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock content %}

        </div>
        <div class="mdl-layout-spacer"></div>
        {% include 'comp/footer.html' %}

    </main>

</div>
{#{% include 'material/includes/material_css.html' %}#}
{#<script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>#}
{#{% include 'material/includes/material_js.html' %}#}
<script src="{% static 'js/material.min.js' %}"></script>

</body>
</html>